### ISSUE TITLE
Adding Duende Identity Server Open ID Connect Blazor authentication to To Do template does not work as expected and freezes browser.

### ISSUE THREAD

**Issue by ghhv** [servicetitan/Stl.Fusion.Samples#23]
Hi Alex,
I've followed the recommended Duende [Blazor BFF code sample ](https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/BFF/BlazorWasm) to add Identity Server Open ID Connect authentication to the To Do template. 

Whilst the OIDC add-on should be standard, there seems to be some incompatibilities with Fusion that cause this to fail. It does recognise the OIDC but attempting to select this will pop up this page and freeze the browser for the original page. 
![image](https://user-images.githubusercontent.com/13160762/178447414-cd8ace3c-531b-4815-acba-8a2fcea176f9.png)

![image](https://user-images.githubusercontent.com/13160762/178444092-b017a003-a8c5-4d79-9306-933df3cf0c0e.png)

I did get it to partially work by completely replacing the your `services.AddAuthentication` with the sample BFF code but navigating to /bff/login instead to login - this opens the Duende demo Identity Server auth page and you can log in with bob/bob or alice/alice. On return to Todo, it does not immediately recognise the login was successful. The /authentication page is unchanged:
![image](https://user-images.githubusercontent.com/13160762/178444691-9c221024-2f55-4123-8c9e-d2d0ddafe350.png)

I added the BFF equivalent auth status page and on navigating to this it now recognises the login:
![image](https://user-images.githubusercontent.com/13160762/178444904-e5330030-beb2-473c-843d-ffc39fd3e9ef.png)

and then navigating back to your /authentication page it is now recognised there too:
![image](https://user-images.githubusercontent.com/13160762/178445065-6deb04aa-0bbe-4a5d-b7d0-3647eeb41714.png)

The To Do app now functions as expected. I'd appreciate if you could please have a quick look to see why it is misbehaving. I have a copy of it available [here ](https://github.com/ghhv/Stl-Fusion-3.2.9-Todo-App-With-OIDC-auth).

Thanks!

**Comment by alexyakunin** [comment]
Hi, can you list the URLs browser goes through during the authentication flow? I am 99% certain it doesn't end with ~/fusion/close URL or any other URL that triggers _Host.cshtml reload.

**Comment by alexyakunin** [comment]
Overall, you need to make sure _Host.cshtml is loaded at last - otherwise ServerAuthHelper.UpdateAuthState won't have a chance to pick up the changes in IPrincipal associated with the current HttpContext.

**Comment by ghhv** [comment]
OK, on launch
https://localhost:5005/
https://localhost:5005/authentication
Selecting Sign In/OIDC goes to here which fails. I have to restart the host after selecting this. https://[localhost](https://localhost:5005/signIn/oidc?returnUrl=https%3A%2F%2Flocalhost%3A5005%2Ffusion%2Fclose%3Fflow%3DSign-in):5005/signIn/oidc?returnUrl=https%3A%2F%2Flocalhost%3A5005%2Ffusion%2Fclose%3Fflow%3DSign-in

Going to /bff/login redirects to here https://demo.duendesoftware.com/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dinteractive.confidential%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A5005%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520api%2520offline_access%26code_challenge%3DZTI7OF6inLd7fkDNGpBCT-6mhlFoGXfory3EiJs_5VQ%26code_challenge_method%3DS256%26nonce%3D637932128153952005.MDA1NGNiMTItYjQ5OC00YTRmLThkMGItNjcwOWQxYTUzZGFlNTBlODkxMWItNGU2Ny00MWE2LWJkYzMtNGNhZGI1NzkxODJm%26state%3DCfDJ8FqtnZBkEBlNujoJLvqfBdMv-VbRHNjo5kVXShbmBabXkB9BbIRL9MctoSb1Dr9ayP3NN48yKq2dxvCg3uIwV_nbhYMhm0FzNGMphyf0CpsP7qjsrF644A_C1T6q8pTO4Ce9ct_rjOWGQeDcEuNnjF9kYNGk7SDIdpjPiF_XagFP9oWt6mUvj4IQkHmCu4khHhBxxia7EGjgRfl8NHDymqDVQXGTTEOP6Bw9tVOMjzwDiqSinGVIcDHozjGYzLilD_DconNFqdWMQljdtPE-LptJemt1dT4ebkpfv2AGjlMlZUNKGMAg5RJQStpPVQrJ-6UJG96-lX03zkiYtI3Y6T02mbvkfKcU0n_jCXqUJ253r0dcgaHQqRg-8RDJmlKRRQ%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D6.10.0.0

The return path in this being https://localhost:5005/signin-oidc

Post login returns to here - https://localhost:5005/

I added this URL https://localhost:5005/bffauth to the menu but for some reason you have to hit enter to make it display the full content as per my pic above..

The switch between Server/Wasm seems to be broken now too. 

Was that what you meant?

**Comment by alexyakunin** [comment]
K, I guess I have to run it - https://localhost:5005/ in the end is good enough to cause auth state to update. I'll share an update tomorrow.

**Comment by ghhv** [comment]
yeah, sorry.. I tried..  pointing it to a an OIDC server seems to be the most flexible way to provide private auth and I guess it should just work like the Github and MS options.. it did my head in..

**Comment by alexyakunin** [comment]
So... A bunch of problems was there. Please do a bit of your own homework next time :)

1. Not sure how you've produced the list of URLs the app passes through on authentication, but here is what I've got:

![image](https://user-images.githubusercontent.com/1673423/179146264-9a0b7efe-b618-4220-a33b-05d58864d2ab.png)

**Comment by alexyakunin** [comment]
If we add `_ssb_`  cookie with `0` value (which switches it to WASM mode), you'd see a much worse pic:

![image](https://user-images.githubusercontent.com/1673423/179146421-2afedb9f-74aa-4b7f-8362-22085b15f554.png)

**Comment by alexyakunin** [comment]
![image](https://user-images.githubusercontent.com/1673423/179146505-5097464e-eca7-4a73-82ab-c2535286cf8c.png)

**Comment by alexyakunin** [comment]
All in all, this is what was off:
- `AntiforgeryHandler` was used only for "backend"-named HTTP clients, so all Fusion (and technically almost every other) requests were blocked
- You shouldn't be manually adding pre-rendered root components
- Authentication was misconfigured.

Check out my comments here: https://github.com/alexyakunin/Fusion-TodoApp-With-OIDC-Auth/commit/cdd57a1faee3e04f775ca0487e70d15c6da3655d , + see the changes I've made after this commit - they're minor, but there are some helpful comments.

**Comment by alexyakunin** [comment]
All commits: https://github.com/alexyakunin/Fusion-TodoApp-With-OIDC-Auth/commits/master

**Comment by ghhv** [comment]
Thank-you.. Will review.

**Comment by ghhv** [comment]
Thanks. I would not have figured that out.
