### ISSUE TITLE
ServerTime.razor

### ISSUE THREAD

**Issue by joriskalz** [servicetitan/Stl.Fusion.Samples#4]
Stl.Fusion.Samples/src/Blazor/Client/Pages/ServerTime.razor contains a refresh button, which pretends to be able to invalidate the state, before the AutoInvalidateTime invalidates it on the server side. However, this is not working due to the reasons you mentioned on https://gitter.im/Stl-Fusion/community

**Comment by joriskalz** [comment]
It has been fixed and it is now working due to () => State.CancelUpdateDelay()

**Comment by alexyakunin** [comment]
Thanks!

**Comment by alexyakunin** [comment]
@joriskalz thanks for closing the issue!
